In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'num':[1,2,3,4,5]})

In [3]:
df

   num
0    1
1    2
2    3
3    4
4    5

In [4]:
#Exercise 1: Square numbers in a column

df['sqaured']  = df['num'].apply(lambda x : x*x)
df

   num  sqaured
0    1        1
1    2        4
2    3        9
3    4       16
4    5       25

In [6]:
#Exercise 2: Even or Odd
df['even_odd'] = df['num'].apply(lambda x: "even" if x% 2 == 0 else "odd")
df

   num  sqaured even_odd
0    1        1      odd
1    2        4     even
2    3        9      odd
3    4       16     even
4    5       25      odd

In [8]:
# Exercise 3: Lowercase names
df['lowercase']  = df['even_odd'].apply(lambda x : x.lower())
df

   num  sqaured even_odd lowercase
0    1        1      odd       odd
1    2        4     even      even
2    3        9      odd       odd
3    4       16     even      even
4    5       25      odd       odd

In [10]:
#Exercise 4: Sum of marks

df_marks = pd.DataFrame({
    'math':[90,80,70],
    'science':[85,75,95],
    'english':[88,92,78]})

In [11]:
df_marks['total'] = df_marks.apply(lambda x : x['math'] + x['science'] + x['english'], axis = 1)
df_marks

   math  science  english  total
0    90       85       88    263
1    80       75       92    247
2    70       95       78    243

In [13]:
#Exercise 5: Best subject

df_marks['best_subject'] = df_marks.apply(lambda x : x.idxmax(), axis = 1)
df_marks  #################################################

   math  science  english  total best_subject
0    90       85       88    263        total
1    80       75       92    247        total
2    70       95       78    243        total

In [14]:
#Exercise 6: Pass/Fail based on total
df_marks['pass_fail'] = df_marks['total'].apply(lambda x : 'pass' if x > 250 else 'fail')
df_marks

   math  science  english  total best_subject pass_fail
0    90       85       88    263        total      pass
1    80       75       92    247        total      fail
2    70       95       78    243        total      fail

In [15]:
# Exercise 7: Conditional bonus marks

df_marks['bonusadded']  = df_marks['total'].apply(lambda x : x + 5 if x < 250 else x)
df_marks

   math  science  english  total best_subject pass_fail  bonusadded
0    90       85       88    263        total      pass         263
1    80       75       92    247        total      fail         252
2    70       95       78    243        total      fail         248

In [ ]:
#  3: String Manipulation (Medium)

In [17]:
df_people = pd.DataFrame({'fullname':['Alice Johnson','Bob Smith','Charlie Brown']})
# extract first name

df_people['first'] = df_people['fullname'].apply(lambda x : x.split()[0])

df_people['last'] = df_people['fullname'].apply(lambda x : x.split()[1])
df_people

        fullname    first     last
0  Alice Johnson    Alice  Johnson
1      Bob Smith      Bob    Smith
2  Charlie Brown  Charlie    Brown

In [18]:
# Exercise 10: Count number of letters in first name
df_people['letter_first']=  df_people['first'].apply(lambda x : len(x))
df_people

        fullname    first     last  letter_first
0  Alice Johnson    Alice  Johnson             5
1      Bob Smith      Bob    Smith             3
2  Charlie Brown  Charlie    Brown             7

In [ ]:
#Part 4: Conditional Column + Numeric Manipulation (Medium-Hard)

In [ ]:
#Exercise 11: Apply discount to price

In [19]:
df = pd.DataFrame({
    'product':['A','B','C','D'],
    'price':[120,80,150,60]
})

In [20]:
df['discounted price'] = df['price'].apply(lambda x : x - (x*0.01) if x > 100 else x)
df

  product  price  discounted price
0       A    120             118.8
1       B     80              80.0
2       C    150             148.5
3       D     60              60.0

In [21]:
# Exercise 12: Categorize price

df['price category'] = df['price'].apply(lambda x : "high" if x > 100 else "low")
df

  product  price  discounted price price category
0       A    120             118.8           high
1       B     80              80.0            low
2       C    150             148.5           high
3       D     60              60.0            low

In [23]:
# Exercise 13: Add tax 5% for all products
df['taxadded'] = df['price'].apply(lambda x : x + x*(0.05))
df

  product  price  discounted price price category  taxadded
0       A    120             118.8           high     126.0
1       B     80              80.0            low      84.0
2       C    150             148.5           high     157.5
3       D     60              60.0            low      63.0

In [25]:
# Part 5: Date Manipulation (Medium-Hard)
import datetime

In [24]:
df = pd.DataFrame({'date':['2026-02-07','2026-02-08','2026-02-09']})

In [26]:
# Exercise 14: Convert string to datetime
df['date']  = pd.to_datetime(df['date'])

In [30]:
# Exercise 15: Extract weekday number
df['weeknum'] = df['date'].dt.weekday
df

        date  weeknum
0 2026-02-07        5
1 2026-02-08        6
2 2026-02-09        0

In [31]:
# Exercise 16: Extract weekday name
df['weekdayname']  = df['date'].dt.day_name()
df

        date  weeknum weekdayname
0 2026-02-07        5    Saturday
1 2026-02-08        6      Sunday
2 2026-02-09        0      Monday

In [ ]:
# Part 6: Harder Lambda + Apply Challenges

In [ ]:
# Exercise 17: Apply discount based on product category

In [32]:
df = pd.DataFrame({
    'product':['A','B','C','D'],
    'price':[120,80,150,60],
    'category':['Electronics','Clothes','Electronics','Toys']
})

In [33]:
df['discountedprice'] = df.apply(lambda row: row['price'] *0.8 if row['category'] == 'Electronics' else row['price'], axis = 1)
df  # row wise operation

  product  price     category  discountedprice
0       A    120  Electronics             96.0
1       B     80      Clothes             80.0
2       C    150  Electronics            120.0
3       D     60         Toys             60.0

In [36]:
# Exercise 18: Combine first and last name into initials
df_people

        fullname    first     last  letter_first
0  Alice Johnson    Alice  Johnson             5
1      Bob Smith      Bob    Smith             3
2  Charlie Brown  Charlie    Brown             7

In [38]:
df_people['initials' ] = df_people.apply(lambda x : x['first'][0] + x['last'][0], axis = 1)
df_people

        fullname    first     last  letter_first initials
0  Alice Johnson    Alice  Johnson             5       AJ
1      Bob Smith      Bob    Smith             3       BS
2  Charlie Brown  Charlie    Brown             7       CB

In [43]:
# Exercise 19: Check if string contains a letter

df_people['check_a']= df_people['first'].apply(lambda x : True if 'a' in x.lower() else False)
df_people

# df_people['check_a'] = df_people['first'].str.contains('a', case=False)

        fullname    first     last  letter_first initials  check_a
0  Alice Johnson    Alice  Johnson             5       AJ     True
1      Bob Smith      Bob    Smith             3       BS    False
2  Charlie Brown  Charlie    Brown             7       CB     True

In [ ]:
# Exercise 20: Create age group

In [44]:
df = pd.DataFrame({'age':[15,22,35,70]})

In [46]:
df['age_group'] = df['age'].apply(lambda x: 'teen' if x < 20 else('Senior' if x>60 else 'Adult'))
df

   age age_group
0   15      teen
1   22     Adult
2   35     Adult
3   70    Senior